### ISSUE TITLE
Consider hook + line survey length/age frequencies if more data for it

### ISSUE THREAD

**Issue by seananderson** [seananderson/pbs-synopsis#14]
Or go crazy and show it all?

**Comment by seananderson** [comment]
Showing IPHC, PHMA N, and PHMA S for all.

E.g., for yelloweye:

![yelloweye-rockfish-ages](https://user-images.githubusercontent.com/19349/36289125-2d6e6972-1273-11e8-94aa-4084696c4958.png)

(sample sizes added too)

**Comment by robynforrest** [comment]
Busy day!
